engines:
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon: 
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 50

ratings:
  paths:
  - "**.py"
  - "**.md"

exclude_paths:
- .codeclimate.yml
